export const USER_WEBSITE_URL =
  process.env.REACT_APP_USER_WEBSITE_URL;
export const BASE_URL = process.env.REACT_APP_API_ENV + '/v1';
export const TOKEN_KEY = 'token';
export const CURRENT_USER_KEY = 'current_user';
export const CURRENT_LANG_KEY = 'current_lang';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const SHOW_UPDATE_FORM = 'SHOW_UPDATE_FORM';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const GET_CHARGE_HISTORY_REQUEST =
  'GET_CHARGE_HISTORY_REQUEST';
export const GET_CHARGE_HISTORY_SUCCESS =
  'GET_CHARGE_HISTORY_SUCCESS';
export const GET_CHARGE_HISTORY_FAILURE =
  'GET_CHARGE_HISTORY_FAILURE';

export const ACTIVE_ACCOUNT_REQUEST = 'ACTIVE_ACCOUNT_REQUEST';
export const ACTIVE_ACCOUNT_SUCCESS = 'ACTIVE_ACCOUNT_SUCCESS';
export const ACTIVE_ACCOUNT_FAILURE = 'ACTIVE_ACCOUNT_FAILURE';

export const WITHDRAW_MONEY_REQUEST = 'WITHDRAW_MONEY_REQUEST';
export const WITHDRAW_MONEY_SUCCESS = 'WITHDRAW_MONEY_SUCCESS';
export const WITHDRAW_MONEY_FAILURE = 'WITHDRAW_MONEY_FAILURE';

export const DEPOSIT_MONEY_REQUEST = 'DEPOSIT_MONEY_REQUEST';
export const DEPOSIT_MONEY_SUCCESS = 'DEPOSIT_MONEY_SUCCESS';
export const DEPOSIT_MONEY_FAILURE = 'DEPOSIT_MONEY_FAILURE';

export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE';

export const GET_COURSE_DETAIL_REQUEST = 'GET_COURSE_DETAIL_REQUEST';
export const GET_COURSE_DETAIL_SUCCESS = 'GET_COURSE_DETAIL_SUCCESS';
export const GET_COURSE_DETAIL_FAILURE = 'GET_COURSE_DETAIL_FAILURE';

export const GET_USER_COURSE_DETAIL_REQUEST =
  'GET_USER_COURSE_DETAIL_REQUEST';
export const GET_USER_COURSE_DETAIL_SUCCESS =
  'GET_USER_COURSE_DETAIL_SUCCESS';
export const GET_USER_COURSE_DETAIL_FAILURE =
  'GET_USER_COURSE_DETAIL_FAILURE';

export const BUY_COURSE_REQUEST = 'BUY_COURSE_REQUEST';
export const BUY_COURSE_SUCCESS = 'BUY_COURSE_SUCCESS';
export const BUY_COURSE_FAILURE = 'BUY_COURSE_FAILURE';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE';

export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST';
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS';
export const DEPOSIT_FAILURE = 'DEPOSIT_FAILURE';

export const GET_USER_COURSES_REQUEST = 'GET_USER_COURSES_REQUEST';
export const GET_USER_COURSES_SUCCESS = 'GET_USER_COURSES_SUCCESS';
export const GET_USER_COURSES_FAILURE = 'GET_USER_COURSES_FAILURE';

export const GET_USER_DASHBOARD_REQUEST =
  'GET_USER_DASHBOARD_REQUEST';
export const GET_USER_DASHBOARD_SUCCESS =
  'GET_USER_DASHBOARD_SUCCESS';
export const GET_USER_DASHBOARD_FAILURE =
  'GET_USER_DASHBOARD_FAILURE';

export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAILURE = 'SEND_CONTACT_FAILURE';

export const TOGGLE_FORGOT_PASSWORD_POPUP =
  'TOGGLE_FORGOT_PASSWORD_POPUP';

export const SEND_FORGOT_PASSWORD_EMAIL_REQUEST =
  'SEND_FORGOT_PASSWORD_EMAIL_REQUEST';
export const SEND_FORGOT_PASSWORD_EMAIL_SUCCESS =
  'SEND_FORGOT_PASSWORD_EMAIL_SUCCESS';
export const SEND_FORGOT_PASSWORD_EMAIL_FAILURE =
  'SEND_FORGOT_PASSWORD_EMAIL_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const GET_ORDER_DETAIL_BY_CODE_REQUEST =
  'GET_ORDER_DETAIL_BY_CODE_REQUEST';
export const GET_ORDER_DETAIL_BY_CODE_SUCCESS =
  'GET_ORDER_DETAIL_BY_CODE_SUCCESS';
export const GET_ORDER_DETAIL_BY_CODE_FAILURE =
  'GET_ORDER_DETAIL_BY_CODE_FAILURE';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAILURE = 'GET_NOTIFICATION_FAILURE';

export const GET_PERMISSION_QUIZ_REQUEST =
  'GET_PERMISSION_QUIZ_REQUEST';
export const GET_PERMISSION_QUIZ_SUCCESS =
  'GET_PERMISSION_QUIZ_SUCCESS';
export const GET_PERMISSION_QUIZ_FAILURE =
  'GET_PERMISSION_QUIZ_FAILURE';

export const GET_QUIZ_REQUEST = 'GET_QUIZ_REQUEST';
export const GET_QUIZ_SUCCESS = 'GET_QUIZ_SUCCESS';
export const GET_QUIZ_FAILURE = 'GET_QUIZ_FAILURE';

export const GET_QUIZ_RANK_REQUEST = 'GET_QUIZ_RANK_REQUEST';
export const GET_QUIZ_RANK_SUCCESS = 'GET_QUIZ_RANK_SUCCESS';
export const GET_QUIZ_RANK_FAILURE = 'GET_QUIZ_RANK_FAILURE';
export const POST_RESULT_QUIZ_REQUEST = 'POST_RESULT_QUIZ_REQUEST';
export const POST_RESULT_QUIZ_SUCCESS = 'POST_RESULT_QUIZ_SUCCESS';
export const POST_RESULT_QUIZ_FAILURE = 'POST_RESULT_QUIZ_FAILURE';

export const GET_TIME_QUIZ_EVENT_REQUEST =
  'GET_TIME_QUIZ_EVENT_REQUEST';
export const GET_TIME_QUIZ_EVENT_SUCCESS =
  'GET_TIME_QUIZ_EVENT_SUCCESS';
export const GET_TIME_QUIZ_EVENT_FAILURE =
  'GET_TIME_QUIZ_EVENT_FAILURE';

export const GET_CHILD_USER_REQUEST =
  'GET_CHILD_USER_REQUEST';
export const GET_CHILD_USER_SUCCESS =
  'GET_CHILD_USER_SUCCESS';
export const GET_CHILD_USER_FAILURE =
  'GET_CHILD_USER_FAILURE';
